/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#d0f0d8",
        "surface-variant": "#caead2",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#614000",
        "on-background": "#042012",
        "surface": "#e9ffed",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#005229",
        "tertiary": "#604000",
        "surface-tint": "#1b6c3d",
        "outline-variant": "#bfc9be",
        "on-primary-container": "#9ae9ae",
        "error-container": "#ffdad6",
        "on-secondary-container": "#7a5747",
        "primary-fixed-dim": "#89d89e",
        "outline": "#707a70",
        "secondary-fixed": "#ffdbcc",
        "on-tertiary-fixed": "#281800",
        "on-primary-fixed": "#00210d",
        "secondary-fixed-dim": "#eabda9",
        "surface-container-low": "#dbfce3",
        "on-surface": "#042012",
        "on-surface-variant": "#404940",
        "background": "#e9ffed",
        "secondary-container": "#ffd0bb",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#fdba49",
        "primary": "#005129",
        "surface-container-highest": "#caead2",
        "on-secondary-fixed": "#2d1509",
        "on-tertiary-container": "#ffd18c",
        "primary-fixed": "#a5f4b8",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#1b3626",
        "on-secondary-fixed-variant": "#5f3f30",
        "surface-bright": "#e9ffed",
        "inverse-on-surface": "#d8f9e0",
        "tertiary-fixed": "#ffddaf",
        "inverse-primary": "#89d89e",
        "surface-container": "#d6f6de",
        "primary-container": "#1a6b3c",
        "surface-container-lowest": "#ffffff",
        "secondary": "#795746",
        "surface-dim": "#c2e2ca",
        "tertiary-container": "#7f5600"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
